name = "steamry"
main = "src/worker.js"
compatibility_date = "2024-04-03"
compatibility_flags = [ "nodejs_compat" ]
workers_dev = false

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"

[triggers]
crons = [ "0 1 * * 1", "0 6 * * *", "*/30 * * * *" ]

[vars]
ORIGIN="https://steamry.rodney.io"
PUBLIC_ORIGIN = "https://steamry.rodney.io"

[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = false

[[d1_databases]]
binding = "DB"
database_name = "steamry"
database_id = "488b4b96-9e71-46ba-a2a6-adef40c44496"
migrations_dir = "drizzle"

[[kv_namespaces]]
binding = "KV"
id = "ee3295e0a30b41f5862cdea8bbde5c25"
